export interface Contact {
  id: string;
  name: string;
  phoneNumber: string;
  avatar?: string;
  createdAt: Date;
}

export interface CallNote {
  id: string;
  contactId: string;
  contactName: string;
  note: string;
  createdAt: Date;
  callStartTime: Date;
  callEndTime: Date;
  callDuration: number; // in seconds
  isAutoGenerated: boolean; // true if "no note was taken"
  callDirection: 'inbound' | 'outbound';
}

export interface IncomingCall {
  contact: Contact;
  startTime: Date;
  direction: 'inbound' | 'outbound';
}

export interface ActiveCall {
  contact: Contact;
  startTime: Date;
  endTime?: Date;
  direction: 'inbound' | 'outbound';
}

export interface Reminder {
  id: string;
  contactId: string;
  contactName: string;
  title: string;
  description?: string;
  dueDate: Date;
  isCompleted: boolean;
  createdAt: Date;
  relatedNoteId?: string;
}

export interface OrderItem {
  id: string;
  name: string;
  description?: string;
  price: number;
  quantity: number;
}

export interface Order {
  id: string;
  contactId: string;
  contactName: string;
  items: OrderItem[];
  totalAmount: number;
  status: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}